### ISSUE TITLE
❤ your screenshot!!

### ISSUE THREAD

**Issue by PySimpleGUI** [hseera/aws-lambda-explorer#1]
You've made my day already!

Thank you for posting a screenshot here.

I like the look of your GUI and found your code super easy to read.

If in the future, you want to be "lazier", you can save a little space.  I hesitate to even mention it because you've done such a wonderful job in your layout section.

Anyway... here's some tricks to save you time maybe.  Again, no complaints about what I see. I love it!

* Text elements defauilt to `""` so no need to specify anything if it's initially blank
* For text and some other elements, you can use a size that's just an `int` if the height is 1. `size=60` is same as `size=(60,1)`
* Keywords `size` and `key` could be hacked to smaller alias of `k` and `s`, but it does make code much less readable
* `InputText` can be `Input` or like you did with `Buttons` where you used `B` and `Text` used `T`, you can use `I` for `Input`
* There's a threading call built in `window.start_thread` that I have started to use with only 2 parms (a lambda that looks like a call to your thread function, and a key should the thread exit).  For me, I like the simple look.  It sets `daemon=True` for you and starts the thread.  Sorry, probably going too far in recommendations :-)

Thanks for using PySimpleGUI, posting a screenshot, and I hope you've enjoyed the process.  Great way to start my day!

![image](https://user-images.githubusercontent.com/46163555/195987281-94493103-fba9-4a5e-a645-7287506d44ab.png)

**Comment by hseera** [comment]
Thank you for your feedback and suggestions.

**Comment by PySimpleGUI** [comment]
You're quite welcome... thank you for the AWESOME program!   I was really excited when I saw your screenshot.  My suggestions were all minor things.... they took up a lot of space, but don't have a big impact overall.  They're more tips and tricks.

Thank you again for starting my day off with a big smile.  Was really enjoyable.
